image: php:5.6-alpine

before_script:
  - apk update -q --no-progress
  - apk add -q --no-progress git curl libpng-dev php5-pear autoconf alpine-sdk
  - docker-php-ext-install gd
  - pecl install xdebug
  - echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so" > /usr/local/etc/php/conf.d/xdebug.ini
  - curl -Os https://getcomposer.org/composer.phar
  - php composer.phar install --prefer-dist -nq

test:
  script:
    - ./vendor/bin/phpcs --standard=PSR1 --encoding=utf-8 --report=emacs --ignore=vendor .
    - ./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 --report=emacs --ignore=vendor .
    - ./vendor/bin/phpunit --coverage-text --colors=never --coverage-html=coverage

  artifacts:
    paths:
      - coverage/
