image: php:5.6-alpine

before_script:
  - apk update -q
  - apk add git curl libpng-dev -q
  - docker-php-ext-install gd
  - curl -O https://getcomposer.org/composer.phar
  - php composer.phar install --prefer-dist

test:
  script:
    - ./vendor/bin/phpunit
