language: php

php:
  - 5.6

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - sudo apt-get update > /dev/null
  - sudo apt-get install curl libpng-dev php5-gd

before_script:
  - composer self-update
  - composer install --prefer-dist -nq

script:
  - ./vendor/bin/phpcs --standard=PSR1 --encoding=utf-8 --report=emacs --ignore=vendor .
  - ./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 --report=emacs --ignore=vendor .
  - ./vendor/bin/phpunit --coverage-text --colors=never --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
